import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import { getServerSession } from 'next-auth'
import SessionProvider from './components/SessionProvider'
import Providers from './components/Provider'
import 'bootstrap/dist/css/bootstrap.min.css';
import { ProvidersTheme } from './providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Thinh Store',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
  
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <ProvidersTheme>
          <Providers>
            <SessionProvider session={session} >
              <div className='dark:bg-gradient-to-b dark:from-slate-300 dark:to-gray-700 bg-gradient-to-b from-[#f4f4f5] to-[#f0dcbb] dark:text-white dark:font-bold'>
                <Header/>
                <div className='pt-[7rem]'>
                  {children}
                </div>
                <Footer/>
              </div>
            </SessionProvider>
            </Providers>
        </ProvidersTheme>
      </body>
    </html>
  )
}
