import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import { getServerSession } from 'next-auth'
import SessionProvider from './components/SessionProvider'
import ColorInversionMarketing from './components/New'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Thinh Store',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
  
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <SessionProvider session={session} >
          <Header/>
          <div style={{marginTop:"7rem",marginBottom:'3rem'}}>
          
            {children}
          </div>
          <Footer/>
        </SessionProvider>
        </body>
    </html>
  )
}
